version: '3.3'

services:
  spp:
    build:
      context: spp
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TESTMODE=${TESTMODE}
      - ETHCLIENTURL=https://ropsten.infura.io/v3/YOURAPIKEY
      - ETHWEBSOCKETURL=wss://ropsten.infura.io/ws/v3/YOURAPIKEY
    ports:
      - "8085:8082"
  pgp:
    build:
      context: pgp-server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ETHCLIENTURL=https://ropsten.infura.io/v3/YOURAPIKEY
      - ETHWEBSOCKETURL=wss://ropsten.infura.io/ws/v3/YOURAPIKEY
    ports:
      - "8084:8080"
