# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = ">=1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = ">=2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/asticode/go-astilectron-bundler", "github.com/jteeuwen/go-bindata", "github.com/rjeczalik/notify"]

# something is broken for this pkg
noverify = ["github.com/dlclark/regexp2"]

# github.com/rjeczalik/notify required only to force master version as v0.9.0 doesn't compile on Mac without CGO
[[constraint]]
  branch = "master"
  name = "github.com/rjeczalik/notify"

[[constraint]]
  branch = "master"
  name = "github.com/asticode/go-astilectron"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = ">=1.3.1"

[[constraint]]
  name = "github.com/coreos/bbolt"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.6" # 1.1.0 breaks windows build

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = ">=1.8.12"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = ">=1.1.1"

[[constraint]]
  name = "github.com/labstack/echo"
  version = ">=3.3.5"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = ">=2.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
 name = "github.com/ethereum/go-ethereum"
 unused-packages = false

[[prune.project]]
  name = "github.com/asticode/go-astilectron-bundler"
  unused-packages = false

[[prune.project]]
  name = "github.com/asticode/go-bindata"
  unused-packages = false

[[prune.project]]
  name = "github.com/asticode/go-astitools"
  unused-packages = false

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  branch = "master"

[[constraint]]
  name = "github.com/natefinch/lumberjack"
  version = ">=2.1.0"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.6.0"
